#Recreate
#Deployment ReCreate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenappdep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  strategy:
    type: Recreate    
  template:
    metadata:
      name: mavenapppod
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavenappcontainer
        image: izi0904/maven-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenappdep
spec:
   selector: 
     app: mavenapp
   ports: 
   - port: 80
     targetport: 8080
     
